### ISSUE TITLE
Make the extension compatible with 1.35.x and later

### ISSUE THREAD

**Issue by kghbln** [mkroetzsch/AutoCreatePage#13]
As reported on [MediaWik.org](https://www.mediawiki.org/wiki/Topic:Wtcswi6lewdvg37g)i master of this extension no longer creates pages with MW 1.37 and later. I myself already realized this when upgrading from 1.31.x to 1.35.x of MediaWiki and master of this extension. Thus the extension potentially already broke somewhere between 1.32.x and 1.34.x. It will be cool to get a fix.

**Comment by kghbln** [comment]
@mkroetzsch FYI since you just updated "your" website to 1.35.x

**Comment by mmarx** [comment]
[We](https://iccl.inf.tu-dresden.de/web/Special:Version) are still running ffcc192 and have not seen any problems with this extension so far: [pages are still getting created automatically](https://iccl.inf.tu-dresden.de/w/index.php?title=Description_Logic_(SS2022)/en&action=history).

Nevertheless, it might still be worthwhile to transition to a proper extension manifest.

**Comment by gesinn-it-gea** [comment]
gesinn.it team is working on updating this extension as well as adding CI. PR will follow.
