### ISSUE TITLE
Unstrip nowiki without accessing mStripState

### ISSUE THREAD

**Issue by mkroetzsch** [mkroetzsch/AutoCreatePage#4]
The code unstrips nowiki blocks from the text that should be placed on the new wiki page. To do this, the parser's internal mStripState member is accessed to get the StripState. This has a public method unstripNoWiki() that does the job. However, the access to mStripState is not declared public and may thus break in the future. A better method should be found. This may require changes in MediaWiki.

**Comment by mmarx** [comment]
This landed as part of #15.
