### ISSUE TITLE
Adding three stripping lines

### ISSUE THREAD

**Issue by kghbln** [mkroetzsch/AutoCreatePage#8]
Taken from the [talk page on mw.o](https://www.mediawiki.org/wiki/Topic:T4eg3wikd9t7rhw8) as a suggestion:

Added 3 lines to AutoCreatePage.php behind [line 94](https://github.com/mkroetzsch/AutoCreatePage/blob/master/AutoCreatePage.php#L94):

```php
$newPageContent = str_replace ( "&#123;" , "{" , str_replace ( "&#125;" , "}" , $newPageContent ) );
$newPageContent = str_replace ( "&#124;" , "|" , $newPageContent );
$newPageContent = str_replace ( "&#34;" , "#" , $newPageContent );
```
This makes the use of templates much easier. Just write in the template what you need with &#123&#59;, &#125&#59, and &#124&#59; and &#34&#59; into a template. Include the template in the parameter, and all works as expected. Made my life much easier...

**Comment by mkroetzsch** [comment]
Thanks, I commented on the talk why I think this is not needed.

**Comment by kghbln** [comment]
Well I have to thank you for providing feedback. Since I am not sure how often you are over there I figured it may be nice to inform you here. Makes more sense anyway since a code change was proposed.

**Comment by mkroetzsch** [comment]
Yes, indeed. I would surely not have seen the talk page if you would not have pointed it out here.
